### ISSUE TITLE
Todo for 0.0.0.5

### ISSUE THREAD

**Issue by AKTheKnight** [AKTheKnight/AKBot#16]
- [x] Spacer line (Do by adding extra line. Then check -1 amount for options)
- [x] Changeable time for refreshing of user list. Do once and then do by changes?
- [x] Option for Display name or username in userlist (Overhead costs)
- [ ] Font size in chat (TrackBar)
- [x] Check that options changes actually change options without restart of clients and bot

**Comment by AKTheKnight** [comment]
Font size is being postponed as it interferes with pre existing changes affecting wrapping
